apiVersion: apps/v1
kind: Deployment
metadata:
  name: javascript-external-scaler
  namespace: javascript-external-scaler-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javascript-external-scaler
  template:
    metadata:
      labels:
        app: javascript-external-scaler
    spec:
      containers:
      - name: scaler
        image: javascript-external-scaler:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: javascript-external-scaler
  namespace: javascript-external-scaler-ns
spec:
  ports:
  - port: 7000
    targetPort: 7000
  selector:
    app: javascript-external-scaler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-1
  namespace: javascript-external-scaler-ns
spec:
  replicas: 0
  selector:
    matchLabels:
      app: test-1
  template:
    metadata:
      labels:
        app: test-1
    spec:
      containers:
      - name: http
        image: nginx:latest
        imagePullPolicy: Always
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test-1
  namespace: javascript-external-scaler-ns
spec:
  scaleTargetRef:
    name: test-1
  pollingInterval: 20
  triggers:
    - type: external
      metadata:
        scalerAddress: javascript-external-scaler.javascript-external-scaler-ns:7000